#cloud-config
# This is a cloud init file to natively install nginx to
#  serve files.
write_files:
    - path: /run/nginx-html/stuff.html
      owner: root:root
      permissions: "0644"
      content: "<p>This is just some stuff</p>"

packages:
  - nginx

runcmd:
    - |
      echo "*** Starting nginx..."
    - systemctl enable nginx
    - systemctl restart nginx
    - |
      echo "*** Installing simple HTML content..."
    - sudo mv /run/nginx-html/stuff.html /usr/share/nginx/html
    
    
